[project]
name = "zimazam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Etienne Perron", email = "etienne.perron@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
]

[project.scripts]
zimazam = "zimazam.flow:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
